# interactive configuration file [USED MY MAIN]
application.config.location=classpath:config.properties
application.version=1.0.0


# -------------------------------
# [MYSQL CONFIGURATION]

# [LOCAL DEVELOPMENT]
mysql.url=jdbc:mysql://localhost:3306/ezeebot
mysql.username=root
mysql.password=password

# [DEVELOPMENT]
# mysql.url=
# mysql.username=
# mysql.password=

# [PRODUCTION]
# mysql.url=
# mysql.username=
# mysql.password=

# campaign completion timeout check [time it will wait for completion of campaign (update the database with 3,6 status)]
grace.completion.timeout=1200000
console.grace.completion.timeout=120000

# Consumer Configuration
# ----------------------
idle.timeout.ms=40000

# Kafka Configuration
# -------------------
kafka.group.id=pinnacle-processor
kafka.fetch.min.bytes=1048576
kafka.fetch.max.wait.ms=1000
kafka.max.partition.fetch.bytes=5242880
kafka.max.wait.time=300000

# TPS Configuration (500 TPS)
# ---------------------------
kafka.num.consumers=1
kafka.max.poll.records=600
kafka.expected.records.per.second=500
kafka.commit.interval.ms=1000
target.tps=500
max.queue.size=60000
cpu.cores=32
http.thread.multiplier=8
http.concurrent.multiplier=48
processing.queue.size=70000

# HTTP Client Configuration
# -------------------------
http.connect.timeout=3000
http.socket.timeout=3000
http.connection.request.timeout=3000 
http.read.timeout=15000
http.write.timeout=15000
rate.adjust.interval.ms=3000

# # InfluxDB Configuration
# # ----------------------
# influxdb.url=http://localhost:8086
# influxdb.token=gGGnbhIWQirhry8iBSYMpcZeetFeclrsVWBVp4UwSZaFk0MmUleoX-RQncFgBiSsnjagHfVC-7sPOSucTevNdA==
# influxdb.org=Pinnacle
# influxdb.bucket=TestBucket

# Prometheus Configuration
# ------------------------
prometheus.port=9091

# JSON Processing Configuration
# -----------------------------
json.processing.batch.size=1000
json.processing.batch.timeout.ms=1000
json.processing.queue.capacity=20000
json.processing.thread.keepalive.seconds=60
json.processing.thread.pool.size=32  
json.processing.thread.queue.size=25000


# -------------------------------
# [KAFKA CLUSTER CONFIGURATION]

# [LOCAL DEVELOPMENT]
kafka.bootstrap.servers=localhost:29094

# # [DEVELOPMENT]
# kafka.bootstrap.servers=

# # [PRODUCTION]
# kafka.bootstrap.servers=

# -------------------------------
# [MONGODB CONFIGURATION]

# [LOCAL DEVELOPMENT]
mongodb.uri=mongodb://localhost:27017/
mongodb.database=callbackdb_testing

# [DEVELOPMENT]
# mongodb.uri=
# mongodb.database=

# [PRODUCTION]
# mongodb.uri=mongodb+srv://wacdc:mT2ijhOGGcIFCCwk@cluster0.xpnowiu.mongodb.net/
# mongodb.database=callbackdb_wacdc


# -------------------------------
# [AWS S3 CONFIGURATION]
aws.accessKey=accessKey
aws.secretKey=secretKey
aws.region=region
aws.s3.bucket=bucket
kafka.consumer.group.id=consumer-group-
kafka.consumer.batch.size=1000